// Generated by Selenium IDE
import org.junit.*;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.junit.Assert.assertTrue;
import static org.openqa.selenium.support.ui.ExpectedConditions.stalenessOf;
import static org.openqa.selenium.support.ui.ExpectedConditions.visibilityOf;

import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.sql.Time;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.TimeUnit;
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class Selenium_test {
    private static WebDriver driver;
    private static WebDriverWait wait;
    private static List<WebElement> list1 = null;
    private static List<WebElement> list2 = null;

    @BeforeClass
    public static void setUp() {
        driver = new ChromeDriver();

        wait = new WebDriverWait(driver, 10 );
        //driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        //driver.manage().timeouts().setScriptTimeout(10, TimeUnit.SECONDS);
        //driver.manage().timeouts().pageLoadTimeout(10, TimeUnit.SECONDS);

    }
    @AfterClass
    public static void tearDown() {
        //driver.quit();
    }
    @Ignore
    @Test
    public void test1() {
        driver.get("https://www.google.com/");
        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("webdriver");
        driver.findElement(By.name("btnK")).click();
    }
    @Test
    public void test11() throws Exception {
        test3();
    }

    @Ignore
    @Test
    public void test2() {

        driver.get("http://localhost/litecart/en/");
        driver.findElement(By.cssSelector("#box-account-login a")).click();
        driver.findElement(By.cssSelector(".content [name=firstname]")).clear();
        driver.findElement(By.cssSelector(".content [name=firstname]")).sendKeys("User11");
        driver.findElement(By.cssSelector(".content [name=lastname]")).clear();
        driver.findElement(By.cssSelector(".content [name=lastname]")).sendKeys("Userovish1");
        driver.findElement(By.cssSelector(".content [name=address1]")).clear();
        driver.findElement(By.cssSelector(".content [name=address1]")).sendKeys("Адрес пользователя 1");
        driver.findElement(By.cssSelector(".content [name=postcode]")).clear();
        driver.findElement(By.cssSelector(".content [name=postcode]")).sendKeys("888888");
        driver.findElement(By.cssSelector(".content [name=city]")).clear();
        driver.findElement(By.cssSelector(".content [name=city]")).sendKeys("Saratov");
        driver.findElement(By.cssSelector(".content [name=email]")).clear();
        driver.findElement(By.cssSelector(".content [name=email]")).sendKeys("email"+ System.currentTimeMillis() +"@mail.ru");
        driver.findElement(By.cssSelector(".content [name=phone]")).clear();
        driver.findElement(By.cssSelector(".content [name=phone]")).sendKeys("8888888888");
        driver.findElement(By.cssSelector(".content [name=newsletter]")).click();
        driver.findElement(By.cssSelector(".content [name=password]")).clear();
        driver.findElement(By.cssSelector(".content [name=password]")).sendKeys("1");
        driver.findElement(By.cssSelector(".content [name=confirmed_password")).clear();
        driver.findElement(By.cssSelector(".content [name=confirmed_password]")).sendKeys("1");
       new Select(driver.findElement(By.cssSelector(".content [name=country_code]"))).selectByValue("AL");
        wait.until(visibilityOf(driver.findElement(By.cssSelector(".content [name=create_account]")))).click();
        //driver.findElement(By.cssSelector(".content [name=create_account]")).click();
    }

    @Test
    public void test3() throws Exception {
        driver.get("http://localhost/litecart/admin/");

        if (driver.findElements(By.id("box-login")).size() > 0) {
            //driver.findElement(By.cssSelector(".input-wrapper [name=username]")).clear();
            wait.until(visibilityOf(driver.findElement(By.cssSelector(".input-wrapper [name=username]")))).sendKeys("admin");
            //driver.findElement(By.cssSelector(".input-wrapper [name=password]")).clear();
            driver.findElement(By.cssSelector(".input-wrapper [name=password]")).sendKeys("admin");
            driver.findElement(By.cssSelector("[name=login]")).click();
        }

        Thread.sleep(400);
        //wait.until(visibilityOf(driver.findElement(By.cssSelector("#box-apps-menu"))));
        driver.findElement(By.cssSelector("#box-apps-menu li:nth-child(5)")).click();


        //wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#box-apps-menu li:nth-child(5)"))).click();
        //wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("#box-apps-menu li:nth-child(5)")));

        //driver.findElement(By.cssSelector("#box-apps-menu li:nth-child(5) a[href='http://localhost/litecart/admin/?app=customers&doc=customers']")).click();
        //driver.findElement(By.partialLinkText("Customers")).click();

        //wait.until(visibilityOf(driver.findElement(By.cssSelector("ul > li:first-child > a")))).click();
        //driver.findElement(By.xpath("(//li)[5]")).click();

        if (list1 == null) {
            list1 = driver.findElements(By.cssSelector(".dataTable tr.row td:nth-child(3)"));
        }else{
            list2 = driver.findElements(By.cssSelector(".dataTable tr.row td:nth-child(3)"));
            //list2.remove(list2.size()-1);
            System.out.println(list1.toString());
            System.out.println(list2.toString());
            System.out.println(list2.containsAll(list1));
            assertTrue(list1.contains(list2));
            //assertTrue(list1.size() == list2.size()-1);
//            if (list1.size() <= list2.size()){
//                throw new IllegalArgumentException("ssssss");
//            }

        }

//        for (WebElement id : list1 ) {
//            System.out.println(id.getText());
//        }

    }
}

